01
Hanwoollim-App/Hanwoollim-Manager pull request #2
Opened 2021-06-22 08:06 UTC by Aperture507

01

2021-06-22 08:11 UTC, DonghyunKim98 requested changes
- 일단 커밋 메세지 부터 컨벤션을 맞춰줘!
   - 해당 내용 노션에 업로드 해놨어
- 두 번째로 하나의 폴더를 더 파지말고 바로 react-native 코드가 나올수있게 해줘.
   - 유저용 어플리케이션의 구조를 보면 무슨 말인지 이해가 될거야.

2021-06-24 10:09 UTC, byungchanKo99 commented on android/gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-6.8-all.zip
이거는 아무 상관 없는건데 실수 >< 안드로이드 빌드할 때 내 컴에선 항상 이 gradle 버전 바꿔줘야 하더라구요...

2021-06-24 11:26 UTC, DonghyunKim98 commented
- 다 끝나면 review 요청부탁드립니다

2021-06-25 10:36 UTC, DonghyunKim98 requested changes

2021-06-25 10:36 UTC, DonghyunKim98 commented on App.tsx
> +}
- 함수형 컴포넌트로 재작성 해주세요.

2021-06-25 10:36 UTC, DonghyunKim98 commented on react-native.config.js
> +  };
- 현재 디자인 팀으로 실질적으로 사용하는 폰트만 전달받은 상태입니다.
- 해당 폰트들을 이용해서 어플리케이션에 적용시킬 준비 해주세요.
- 관련 명령어는 `npx react-native link` 입니다.
- [참고사이트](https://medium.com/@danielskripnik/how-to-add-and-remove-custom-fonts-in-react-native-b2830084b0e4)

2021-06-25 10:37 UTC, DonghyunKim98 requested changes

2021-06-25 10:37 UTC, DonghyunKim98 commented on app/App.tsx
> +}
- 함수형 컴포넌트로 재작성해주세요.

2021-06-26 08:21 UTC, DonghyunKim98 approved these changes

2021-06-26 09:19 UTC, merged