feat: customModal 제작
Hanwoollim-App/Hanwoollim-Manager pull request #3
Opened 2021-07-12 04:50 UTC by byungchanKo99

<img src = "https://user-images.githubusercontent.com/70642609/125232250-2b96fb00-e317-11eb-9187-5f84e32b2e68.jpg" width="400px">
컴포넌트 프로퍼티

- mdVisible : boolean, 모달창 출력 결정
- title : string, 제목
- subTitle : string, 소제목
- buttonList : Array<customBtnType>, 출력할 버튼 리스트

customBtnType와 customModal props interface는 customModalUtils에 있습니다.

ex)
```
const modalBtn: Array<customBtnType> = [
    {
      buttonText: '1번',
      buttonClickListener: changeVisible,
    },
    {
      buttonText: '2번',
      buttonClickListener: changeVisible,
    },
    {
      buttonText: '3번',
      buttonClickListener: changeVisible,
    },
  ];
...
...
...
 <CustomModal
          mdVisible={modalVisible}
          title={'타이틀 테스트'}
          subtitle={'서브타이틀 테스트'}
          buttonList={modalBtn}
        />
```

2021-07-14 07:27 UTC, Aperture507 approved these changes, later dismissed

2021-07-18 23:29 UTC, DonghyunKim98 commented
- `pod install` 이 안되어 있네요 😅  
- 진행하고 commit 올립니다.

2021-07-18 23:35 UTC, DonghyunKim98 commented
@byungchanKo99 modal 창을 확인할 수 있는 버튼 자체가 없어서, 리뷰가 어렵습니다. 임시적으로 버튼을 만든다음에 다시 리뷰를 요청해주세요.

2021-07-18 23:43 UTC, DonghyunKim98 requested changes

2021-07-18 23:43 UTC, DonghyunKim98 commented on app/components/common/CustomModal.tsx
> +    elevation: 5,
- ios 대응도 해주세요!

2021-07-18 23:43 UTC, DonghyunKim98 commented on app/components/common/CustomModal.tsx
> +  BtnListStyle: {
- 대문자로 시작하는건 좋지 않습니다.
- 또 굳이 Style 을 붙이는것도 좋지 않습니다.
```suggestion
 bntList: {
```

2021-07-18 23:43 UTC, DonghyunKim98 commented on app/components/common/CustomModal.tsx
> +        )}
- && 를 써서 불필요한 삼항 연산자를 없애주세요.
```suggestion
        {second !== undefined && (
          <CustomBtn
            title={second.buttonText}
            onClickListener={second.buttonClickListener}
            titleStyle={styles.BtnListTitleStyle}
            btnStyle={styles.whiteLastBtn}
          />
        )}
```

2021-07-18 23:43 UTC, DonghyunKim98 commented on app/components/common/CustomModal.tsx
> +  const second = buttonList.pop(); // if the array is empty, return undefined
- 전달받은 props 를 **하위 컴포넌트에서 변경하는 것은 매우 안좋은 방식**입니다. 
- 정직하게 `buttonList[2]` 등으로 접근하는 것도 하나의 방식입니다. 
   - 아니라면,  Spread Operator 를 사용하는 것은 어떤가요?
   - `const [first, second, last] = buttonList`
- 또한 type 도 명시되어 있지 않네요. 😅

2021-07-19 12:27 UTC, DonghyunKim98 requested changes

2021-07-19 12:27 UTC, DonghyunKim98 commented on app/components/screens/home/Home.tsx
> +        <BtnWithIcon
- 이 컴포넌트 네이밍이 아쉽습니다.
- 아이콘이 있는 버튼 이라는 의미를 가지는데 실상은 아래 캡쳐된 컴포넌트잖아요? 
   - 버튼의 느낌보다는 Navigation 을 하는 Banner 의 느낌이 더 강합니다.
   - 다른 네이밍으로 바꿔주시길 바랍니다.
   

![image](https://user-images.githubusercontent.com/60422588/126159307-fe7a7675-cd58-426c-9225-2d4121054831.png)

2021-07-19 12:27 UTC, DonghyunKim98 commented on app/components/common/CustomModal.tsx
>      elevation: 5,
- 여전히 ios 대응이 안되어있는게 있네요 🥲

2021-07-19 12:27 UTC, DonghyunKim98 commented on app/components/common/CustomModal.tsx
> +  const [last, second, ...args]: Array<customBtnType | undefined> = [
- args 라는 네이밍이 무엇을 의미하는지 와닿지 않습니다.
- 실질적으로는 CustomModal 에 버튼이 3개이상은 아니니깐, `first` 로 명명해도 혼선은 없어 보입니다.

2021-07-19 14:56 UTC, DonghyunKim98 requested changes

2021-07-19 14:56 UTC, DonghyunKim98 commented on app/components/common/Banner.tsx
> +function Banner({
- 여전히 마음에 안드는데... ㅋㅋㅋㅋㅎㅎㅎㅎ
- Navigation 만을 담당하니깐 `NavigationBlock` 은 어떻습니까??

2021-07-19 15:53 UTC, DonghyunKim98 approved these changes

2021-07-20 09:39 UTC, merged