Feat/notice
Hanwoollim-App/Hanwoollim-Manager pull request #4
Opened 2021-07-19 10:27 UTC by Aperture507

2021-07-20 13:13 UTC, DonghyunKim98 requested changes

2021-07-20 13:13 UTC, DonghyunKim98 commented on app/components/screens/notice/Notice.tsx
> +            source={require('../../../assets/images/searchIcon.png')}
- asset 은 위로 따로 빼주세요.

2021-07-20 13:13 UTC, DonghyunKim98 commented on app/components/screens/notice/Notice.tsx
> +  },
- Object 의 key 값은 대문자로 보통 시작하지 않습니다.
- `style` 이라는 부분이 겹칩니다. 제외시켜주세요.

2021-07-20 13:13 UTC, DonghyunKim98 commented on app/components/screens/notice/Notice.tsx
> +  },
- 객체 안의 key 값은 대문자로 시작하지 않습니다!

2021-07-20 13:13 UTC, DonghyunKim98 commented on app/components/screens/notice/Notice.tsx
> +    marginTop: heightPercentage(-4),
- 제대로 구동은 안해봐서 모르는데, - 값을 주어야 퍼블리싱이 나오나요?

2021-07-20 13:13 UTC, DonghyunKim98 commented on app/components/screens/notice/Notice.tsx
> +    fontSize: 12,
- 반응형 작업해주세요 😅

2021-07-20 13:15 UTC, DonghyunKim98 commented
### 7.20 오후 10시 13분
- 크게 공통적으로 보이는 부분은 3가지 입니다.
    1. 반응형 작업이 덜 되어 있다.
    2. 네이밍 규칙을 지키지 못하고 있다.
    3. type 을 명시하지 못하고 있다.
- 위 3가지만 먼저 해결하시면 될 것 같습니다. `FlatList` 관련 Typescript 코드는 조만간 또 공유해드리겠습니다!

2021-07-21 05:12 UTC, Aperture507 commented on app/components/screens/notice/Notice.tsx
> +    marginTop: heightPercentage(-4),
Member.tsx 의 37번째 줄의 imageStyle 값에서도 
marginLeft: widthPercentage(-40)
처럼 -값을 줬는데, 검색창이랑 검색 돋보기 아이콘을 flexDirection: 'row' 로 묶어서 넣으니까 검색창 뒤에 돋보기 아이콘이 로드됩니다. 
![Simulator Screen Shot - iPhone 12 - 2021-07-21 at 14 06 13](https://user-images.githubusercontent.com/81297398/126434005-0dd455ba-570e-4ef6-8a98-557a229bd47b.png)

근데 원하는건 검색창 안에 돋보기 아이콘이 있는 것이니까 그럼 <TextInput/> 안에 <Image/>를 넣으면 되나..? 라고 생각했는데 그런 방식은 또 불가능하고 그래서 일단은 -40값을 주어서 왼쪽으로 움직여서 억지로 겹치게 한 느낌입니다. 

저는 이 돋보기 모양을 터치해야 검색되는게 아니고 검색어를 넣자마자 바로바로 결과값이 로드되는 형식으로 일단 생각하고 있어서 단순 장식으로만 생각하고 있는지라 이렇게 대충 위치만 맞게 넣었는데, 이 부분 관련해서도 논의가 필요할 것 같습니다.


pr 주신 -4값 가진 것도 단순 표시이기 때문에 큰 상관 없을 것 같아서 그렇게 했습니다

(marginTop: heightPercentage(0), 준 화면)
![Simulator Screen Shot - iPhone 12 - 2021-07-21 at 14 10 53](https://user-images.githubusercontent.com/81297398/126434365-c3f8b0e8-8bc1-4b06-be93-9c2e68f9e1b5.png)

2021-07-21 05:50 UTC, DonghyunKim98 commented on app/components/screens/notice/Notice.tsx
> +    marginTop: heightPercentage(-4),
### 상단 TextInput 관련
```tsx
<View>
   <TextInput/>
   <FontAwesomeIcon>
</View>
```
이런식으로 짜면 됩니다.

2021-07-21 05:58 UTC, Aperture507 commented on app/components/screens/notice/Notice.tsx
> +    marginTop: heightPercentage(-4),
어... FontAwesomeIcon으로 로컬 이미지 파일을 불러오는 것도 가능한건가요?

2021-07-21 06:05 UTC, DonghyunKim98 commented on app/components/screens/notice/Notice.tsx
> +    marginTop: heightPercentage(-4),
아 로컬 이미지 파일이야? 너가 직접 찾은?
그러면 `Image` 로 진행하면 되지!

2021-07-21 06:15 UTC, Aperture507 commented on app/components/screens/notice/Notice.tsx
> +    marginTop: heightPercentage(-4),
성진님이 올려주신 PNG 파일 씁니다 
```tsx
        <View style={styles.searchSection}>
          <TextInput
            style={styles.searchTextInput}
            placeholder="검색"
            placeholderTextColor="#a2a2a2"
          />
          <Image source={searchIcon} style={styles.imageStyle} />
        </View>
```
현재 코드 형태랑 무언가 다른건가요?

2021-07-21 06:28 UTC, DonghyunKim98 commented on app/components/screens/notice/Notice.tsx
> +    marginTop: heightPercentage(-4),
```tsx
searchSection: {
    width: '90%'
    height: heightPercentage(58),
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderRadius: widthPercentage(10),
    backgroundColor: 'white',
  },
  searchTextInput: {
    width: '85%',
    height: '80%',
    fontSize: fontPercentage(20),
    lineHeight: fontPercentage(25),
    fontFamily: 'NotoSansKR-Bold',
    paddingLeft: widthPercentage(13),
  },
  imageStyle: {
    width: widthPercentage(25),
    height: heightPercentage(25),
    resizeMode: 'contain',
  },
```

2021-07-21 06:28 UTC, DonghyunKim98 commented on app/components/screens/notice/Notice.tsx
> +    marginTop: heightPercentage(-4),
이런식으로 퍼블리싱 할 것 같습니다. 참고해주세요

2021-07-21 06:28 UTC, DonghyunKim98 commented on app/components/screens/notice/Notice.tsx
> +    marginTop: heightPercentage(-4),
부모에다가 `justifyContent` 랑 `alignItems` 를 걸어야합니다~

2021-07-21 06:43 UTC, DonghyunKim98 commented on app/components/screens/notice/Notice.tsx
> +    marginTop: heightPercentage(-4),
```tsx
roleSection: {
    flexDirection: 'row',
    marginTop: heightPercentage(15),
    marginLeft: widthPercentage(23),
    alignItems: 'center', // 추가됨
  },
  ```
  이렇게 부모에 정렬 걸어주면 됩니다.

2021-07-22 09:44 UTC, DonghyunKim98 requested changes

2021-07-22 09:44 UTC, DonghyunKim98 commented on app/components/screens/member/Member.tsx
> +  const renderItem: ({item}: {item: Array}) => any = ({item}) => (
- Array 에 대한 Generic type 이 명시되어 있지 않습니다. 명시해주세요.
- 그리고 Array 가 넘어오는게 맞나요? item 하나만 넘어오는걸로 알고있습니다.

2021-07-22 09:44 UTC, DonghyunKim98 commented on app/components/screens/member/Member.tsx
> +  };
- Member 함수와 직접적인 관계가 없습니다. Member 함수 밖으로 빼주세요.

2021-07-22 09:44 UTC, DonghyunKim98 commented on app/components/screens/member/Member.tsx
> +);
- Student 경우, FlatList 의 자식 요소로 쓰이는데 이럴 경우 `React.memo()` 를 이용해서 성능 최적화를 하는게 좋습니다.
- Member Component 가 업데이트 될때, FlatList 의 모든 Student 가 Virtual DOM 과 비교하면 어플이 느려지기 때문이죠.
- 새로운 파일로 분리해주세요.

2021-07-23 03:53 UTC, Aperture507 commented on app/components/screens/member/Member.tsx
> +  const renderItem: ({item}: {item: Array}) => any = ({item}) => (
<img width="631" alt="스크린샷 2021-07-23 오후 12 48 36" src="https://user-images.githubusercontent.com/81297398/126735515-b154a22c-e6b5-4e83-83f9-c6e66aa9e153.png">
Generic type에 대한 피드백은 저번에 이렇게 받긴했습니다. 린트 에러는 안뜨는데 vscode상에서는 빨간줄에 타입 명시 안되있다고 저도 뜨긴 하네요. 음...근데 저번에 이 에러 해결하려고 좀 여러가지 시도해봤는데 결국 안없어졌어서...

2021-07-23 03:56 UTC, Aperture507 commented on app/components/screens/member/Member.tsx
> +  const renderItem: ({item}: {item: Array}) => any = ({item}) => (
Array로 받는 것은 그냥 뭔가 item 안에 name, major, studentCode 가 있어서 Array로 당연히 받은 느낌이긴 한데, 지금 any 로 바꿔보니 빨간줄 없어지네요. any로 갈까요??

2021-07-23 03:57 UTC, DonghyunKim98 commented on app/components/screens/member/Member.tsx
> +  const renderItem: ({item}: {item: Array}) => any = ({item}) => (
- 반환타입을 명시 안해도 된다 라는 의미는 "함수의 반환타입"을 명시하지 않아도 된다 라는 의미였습니다.
- 즉 아래와 같이 코드를 고치는게 어떻겠냐 라는 의미였죠
```
const renderItem = ({item} : {item : Array<???>}) => {
 //rest of codes go here...
}
```

2021-07-23 03:58 UTC, Aperture507 commented on app/components/screens/member/Member.tsx
> +  const renderItem: ({item}: {item: Array}) => any = ({item}) => (
넵 근데 저 <>안에 하나밖에 안들어가잖아요? 근데 item 값은 string도 있고 number도 있고 그래서 뭔가 생각을 그만뒀었어요 ㅋㅋ

2021-07-23 03:59 UTC, DonghyunKim98 commented on app/components/screens/member/Member.tsx
> +  const renderItem: ({item}: {item: Array}) => any = ({item}) => (
- name, major, studentCode 등을 담은 interface 를 만들면 될것같습니다 ㅎㅎ

2021-07-23 03:59 UTC, Aperture507 commented on app/components/screens/member/Member.tsx
> +  const renderItem: ({item}: {item: Array}) => any = ({item}) => (
크아악 그냥 array 말고 any로 가면 안되나요 ㅋㅋㅋ

2021-07-23 04:00 UTC, DonghyunKim98 commented on app/components/screens/member/Member.tsx
> +  const renderItem: ({item}: {item: Array}) => any = ({item}) => (
그러면 ts 를 쓰는 의미가없습니다 😭
지금 무슨 타입이 오는지 모르는게 아닌데, 명시해주세요

2021-07-23 05:33 UTC, DonghyunKim98 requested changes

2021-07-23 05:33 UTC, DonghyunKim98 commented on app/components/common/NoticeItemType.tsx
> +export interface NoticeItemType {
- `NoticeItemInterface`
로 네이밍 바꾸어주세요!

2021-07-23 05:33 UTC, DonghyunKim98 commented on app/components/common/Student.tsx
> +const Student: React.FC<StudentType> = ({
- React Component 는 Arrow Function 말고 function 키워드를 사용해서 나타내기로 약속했습니다~!
- `function Student()` 로 나타내주세요!

2021-07-23 05:33 UTC, DonghyunKim98 commented on app/components/common/StudentType.tsx
> +export interface StudentType {
- 역시 `StudentInterface` 로 바꾸어주세요 ㅎㅎ

2021-07-23 05:33 UTC, DonghyunKim98 commented on app/components/screens/notice/Notice.tsx
> -            renderItem={renderItem}
- 역시 item 의 타입을 명시해주세요!

2021-07-23 05:37 UTC, DonghyunKim98 requested changes

2021-07-23 05:37 UTC, DonghyunKim98 commented on app/components/screens/notice/Notice.tsx
> +            renderItem={({item}) => (
- 이 부분입니다 item 타입 명시해주세요!

2021-07-25 03:06 UTC, DonghyunKim98 approved these changes

2021-07-25 03:14 UTC, merged