Feat/NoticeNavigator
Hanwoollim-App/Hanwoollim-Manager pull request #6
Opened 2021-07-27 06:10 UTC by Aperture507

2021-07-27 08:11 UTC, DonghyunKim98 requested changes

2021-07-27 08:11 UTC, DonghyunKim98 commented on app/components/screens/notice/NoticeItem.tsx
> +  const NoticeClickListener = async () => {
- 왜 async 가 있나요?

2021-07-27 08:11 UTC, DonghyunKim98 commented on app/components/screens/notice/NoticeItem.tsx
> +    navigation.navigate('NoticeNavigator');
- NoticeDetail 로 고쳐야합니다. Screen 이름을 줘서 네비게이팅 하는 방식이에요.

2021-07-28 09:28 UTC, DonghyunKim98 commented
### 리뷰 사항
- 공지사항 _삭제하기_ 버튼을 누른 다음에 _삭제했습니다._  모달창이 뜨고, 확인을 눌렀을때 이전화면 (공지사항 목록) 으로 돌아가도록 해주세요.
- 공지사항 등록하기 에서 제목을 입력하면 회색이 아닌 **검정색으로** 글씨가 나타나게 해주세요.
    - placeholder 값만 회색으로 해주세요.
- 공지사항 본문은 외부 라이브러리를 씁니다.quill 을 지원하는 api 중에서 골라주시면 될것같아요.
   - 검색해봤는데 https://github.com/imnapo/react-native-cn-quill 이런 레포가 나오네요!
- _공지사항 등록하기_ 버튼을 누른 다음에 _등록했습니다_  모달창이 뜨고, 확인을 눌렀을 때 이전화면 (공지사항 목록)으로 돌아가도록 해주세요.

2021-07-29 06:50 UTC, DonghyunKim98 requested changes

2021-07-29 06:50 UTC, DonghyunKim98 commented on app/components/screens/notice/NoticeUpload.tsx
> +          <TextInput style={styles.postTitleBoxText} placeholder="제목" />
- placeholderTextColor 값은 남겨주시고, 실제 입력을 했을때 글자 색만 변경해주시면 됩니다.

2021-07-29 06:50 UTC, DonghyunKim98 commented on app/components/screens/notice/NoticeUpload.tsx
> +  const [modalVisible, setModalVisible] = useState(false);
- useState 타입 명시해주세요

2021-07-29 06:50 UTC, DonghyunKim98 commented on app/components/screens/notice/NoticeUpload.tsx
> +  function changeVisible() {
- Component 내부에서 사용되는 함수의 경우에는 Arrow Function 으로 정의하기로 약속했습니다.
- - Arrow Function 으로 바꾸어주세요.

2021-07-29 06:50 UTC, DonghyunKim98 commented on app/components/screens/notice/NoticeUpload.tsx
> +  const modalBtn: Array<customBtnType> = [
- 굳이 NoticeUpload Component 내부에 선언될 이유가 있나요?

2021-07-29 07:04 UTC, Aperture507 commented on app/components/screens/notice/NoticeUpload.tsx
> +  const modalBtn: Array<customBtnType> = [
어,,,안되나요??

2021-07-29 07:06 UTC, DonghyunKim98 commented on app/components/screens/notice/NoticeUpload.tsx
> +  const modalBtn: Array<customBtnType> = [
- modalBtn 이 왜 NoticeUpload 내부에 선언되어야 하나 라고 물어보는건데, 내부에 선언되어야만 하네요
- `returnToMain()` 을 쓸려면 그렇게 해야하는 군요.

2021-07-29 07:06 UTC, Aperture507 commented on app/components/screens/notice/NoticeUpload.tsx
> +  const modalBtn: Array<customBtnType> = [
네네

2021-07-29 07:11 UTC, DonghyunKim98 commented
- 삭제하기 나 등록하기 버튼을 ** 아래에서 얼마만큼 떨어진 곳**에 배치하고 싶다 는 가능은 한데, 추천드리지 않습니다.
- 웹 퍼블리싱은 (RN은 웹 퍼블리싱 기반이니깐) **쌓기맥락** 이라는 것이 존재하고, 위에서 아래로, 왼쪽에서 오른쪽으로 쌓아집니다.
- 굳이 아래에서 위로 쌓기 맥락을 바꾸고 싶다면 flexDirection값을 column-reverse 로 바꿔서 하면 됩니다.

2021-07-29 07:16 UTC, DonghyunKim98 requested changes

2021-07-29 07:16 UTC, DonghyunKim98 commented on app/components/screens/notice/NoticeDetail.tsx
> +  root: {
-  root 에 alignItems 를 center 로 주시면, 하위 JSX 들에게 marginLeft 를 주지 않아도 됩니다. (자동 중앙정렬)
- 이전에도 비슷하게 짜셔서 제가 수정드렸었습니다. (FlatList) 확인해보세요!

2021-07-29 07:23 UTC, DonghyunKim98 requested changes

2021-07-29 07:23 UTC, DonghyunKim98 commented on app/components/screens/notice/NoticeDetail.tsx
> +  btnStyle: {
- 여기도 alignItems : center 과 justifyContent : center 를 넣으면...!?!
- 중앙에 정렬되어 있다면 굳이 하위 JSX에 margin을 쓸 필요가 없답니다!

2021-07-29 07:40 UTC, Aperture507 commented on app/components/screens/notice/NoticeDetail.tsx
> +  btnStyle: {
어... 이부분은 post라는 스타일을 가지는 본문이 표시되는 부분인 것 같은데, 본문이 하얀색 박스 안에 적절한 위치에서부터 표시될 수도 있도록 일부러 margin값을 준 것이긴 합니다. alignItems : center 과 justifyContent : center를 넣고 따로 padding값을 주는게 더 괜찮을 수도 있을 것 같네요!

2021-07-29 07:43 UTC, DonghyunKim98 commented on app/components/screens/notice/NoticeDetail.tsx
> +  btnStyle: {
확인했습니다~ 전반적으로 퍼블리싱 다시 훑어보면서 marginLeft 등을 허투로 준건 없는지 확인해주세요

2021-07-29 07:43 UTC, Aperture507 commented on app/components/screens/notice/NoticeDetail.tsx
> +  btnStyle: {
아 아니다. width height값 주고 alignItems : center 과 justifyContent : center만 쓰는게 제일 깔끔하겠네요 멍청하네 ;

2021-07-29 07:43 UTC, DonghyunKim98 commented
다 끝나시면, 퍼블리싱 결과물 다시 스크린샷찍어서 PR 업데이트해주세요

2021-07-29 08:25 UTC, DonghyunKim98 requested changes

2021-07-29 08:25 UTC, DonghyunKim98 commented on app/components/screens/notice/NoticeUpload.tsx
> +    borderRadius: 10,
- 반응형 작업!

2021-07-29 08:25 UTC, DonghyunKim98 commented on app/components/screens/notice/NoticeUpload.tsx
> +    borderRadius: 10,
- 반응형 작업!

2021-07-29 08:25 UTC, DonghyunKim98 commented on app/components/screens/notice/NoticeUpload.tsx
> +    borderRadius: 21,
-반응형 작업!

2021-07-30 05:41 UTC, Aperture507 commented on app/components/screens/notice/NoticeUpload.tsx
> +    borderRadius: 21,
borderRadius값도 반응형으로 작업해야하나요??

2021-07-30 05:49 UTC, DonghyunKim98 reviewed
LGTM 👍
4시간후쯤에 실제 작동시켜보고 코드 더 뜯어보겠습니다.

2021-07-30 10:01 UTC, DonghyunKim98 requested changes

2021-07-30 10:01 UTC, DonghyunKim98 commented on app/components/screens/notice/NoticeItem.tsx
>      marginHorizontal: 14,
- 반응형 작업!

2021-07-30 10:01 UTC, DonghyunKim98 commented on app/components/screens/notice/index.tsx
>      shadowRadius: 6,
- shadowRadius 도 반응형 작업이 필요합니다. 😅

2021-07-31 05:10 UTC, DonghyunKim98 approved these changes

2021-08-01 02:30 UTC, merged