Feat/sign in
Hanwoollim-App/Hanwoollim-Manager pull request #8
Opened 2021-08-04 07:22 UTC by Aperture507

초기 화면 이후 로그인 창의 PR입니다
--------------------------------
<img src="https://user-images.githubusercontent.com/81297398/128138693-465e7fb9-b69d-4506-8af2-492a4af15ce2.png" width=350 height=750>

2021-08-04 10:36 UTC, DonghyunKim98 requested changes

2021-08-04 10:36 UTC, DonghyunKim98 commented on app/components/screens/signIn/index.tsx
> +            <Text>로그인 실패</Text>
- `<Text>` 에 스타일이 부여되어  있지 않습니다.

2021-08-04 10:36 UTC, DonghyunKim98 commented on app/components/screens/signIn/index.tsx
> +        <View style={styles.middleGap}></View>
- `<View style={styles.middleGap}/>` 으로 자식 컴포넌트가 없는경우 1줄로 표현할 수 있습니다.

2021-08-04 10:36 UTC, DonghyunKim98 commented on app/components/screens/signIn/index.tsx
> +          </View>
- 의미없는 View 감싸기 아닌가요?

2021-08-04 10:36 UTC, DonghyunKim98 commented on app/components/screens/signIn/index.tsx
> +  const [pw, setPw]: [string, Function] = useState('');
- `useState<>` 형식으로 type 표시 변경해주세요.

2021-08-05 01:50 UTC, Aperture507 commented on app/components/screens/signIn/index.tsx
> +            <Text>로그인 실패</Text>
로그인 실패했을 때 모달 창을 보여주기 위해 만든 임시 버튼이라 style 지정은 따로 하지 않았습니다

2021-08-05 02:04 UTC, Aperture507 commented on app/components/screens/signIn/index.tsx
> +  const [pw, setPw]: [string, Function] = useState('');
```tsx
export interface UserId {
  id: string;
  setId: Function;
}

export interface UserPw {
  pw: string;
  setPw: Function;
}

function SignIn() {
  const navigation: NavigationProp<ParamListBase> = useNavigation();
  const headerLogo = require('../../../assets/images/HanwoollimWhite.png');
  const [id, setId] = useState<UserId | any>();
  const [pw, setPw] = useState<UserPw | any>();```
요런식으로 바꿔보긴 했는데 이렇게 해야할 이유가 뭔가요?

2021-08-05 02:08 UTC, DonghyunKim98 commented on app/components/screens/signIn/index.tsx
> +  const [pw, setPw]: [string, Function] = useState('');
- https://velog.io/@jjburi/TypeScript-useState%EC%97%90%EC%84%9C-type-%EC%A7%80%EC%A0%95
- type을 useState<> 식으로 지정하는게 보편적이기 때문입니다. (굳이 setState 가 Function 인걸 명시할 필요가 없어집니다.)
- 그리고 지금 이 코드에서 any 가 반드시 쓰여하는건가요?
   - state 의 기본값을 넣어주면 해결될것 같습니다.

2021-08-05 02:11 UTC, DonghyunKim98 requested changes

2021-08-05 02:11 UTC, DonghyunKim98 commented on app/components/screens/signIn/index.tsx
> +  const [pw, setPw] = useState<UserPw | any>();
```tsx
  const [id, setId] = useState<string>();
  const [pw, setPw] = useState<string>();
```
으로만 해도 됩니다. comment 로 달아놨던 링크 참고해주세요.

2021-08-05 05:12 UTC, Aperture507 commented on app/components/screens/signIn/index.tsx
> +  const [pw, setPw] = useState<UserPw | any>();
<img width="700" alt="스크린샷 2021-08-05 오후 2 10 50" src="https://user-images.githubusercontent.com/81297398/128294407-ff752534-57b8-4702-97f2-1f82db8394e7.png">

이렇게 에러가 뜨긴해서 any를 추가했었습니다. 그냥 무시할까요?

2021-08-05 05:16 UTC, DonghyunKim98 commented on app/components/screens/signIn/index.tsx
> +  const [pw, setPw] = useState<UserPw | any>();
```tsx
  const [id, setId] = useState<UserId>('');
  const [pw, setPw] = useState<UserPw>('');
```

- initial state 값을 넣으면 됩니다. 초기 값이 아무것도 없어서 undefined 가 뜨는 것입니다.

2021-08-07 04:48 UTC, DonghyunKim98 approved these changes

2021-08-07 07:25 UTC, merged